security:
    firewalls:
        frontend:
            http_basic: 
                provider: users
            pattern:  ^/*
            anonymous: ~
            form_login:
                login_path: usuario_login
                check_path: usuario_login_check
            logout:
                path: usuario_logout
                target: /
                invalidate_session: false
            remember_me:
                key:    admin
                lifetime: 3600

    access_control:
        - { path: ^/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/*, roles: ROLE_USUARIO }
        - { path: ^/user/loguer, roles: ROLE_USUARIO }

    providers:
        users:
            entity: { class: InstantMovie\BackendBundle\Entity\User, property: email }

    encoders:
        #InstantMovie\BackendBundle\Entity\User: { algorithm: sha512, iterations: 10}
        InstantMovie\BackendBundle\Entity\User: plaintext

