parameters:
#    frontend.example.class: InstantMovie\FrontendBundle\Example

services:
#    frontend.example:
#        class: %frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    login_listener:
        class: InstantMovie\FrontendBundle\Listener\LoginListener
        arguments: [@router]
        tags:
            - { name: kernel.event_listener, event:security.interactive_login }
            - { name: kernel.event_listener, event: kernel.response }
