#!/usr/bin/env php
<?php

// include the composer autoloader
require_once __DIR__ .'/../vendor/autoload.php'; 
require_once __DIR__ .'/src/Command/WorkerCommand.php';
require_once __DIR__.'/../app/AppKernel.php';

// import the Symfony Console Application 
use Symfony\Bundle\FrameworkBundle\Console\Application;
use src\Command\WorkerCommand; 
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;



$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';

if ($debug) {
    Debug::enable();
}

$kernel = new AppKernel($env, $debug);
$application = new Application($kernel);
$application->add(new WorkerCommand());
$application ->run();
?>
